name: 'casa_e_patas'
version: '1.0.0'
config-version: 2

profile: 'casa_e_patas'

flags:
  send_anonymous_usage_stats: false

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  casa_e_patas:
    +persist_docs:
      relation: true
      columns: true
    silver:
      +materialized: view
    gold:
      +materialized: table
      +schema: gold